"""initial schema

Revision ID: 1647c58b0e84
Revises: 
Create Date: 2026-10-02 12:31:14.569990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1647c58b0e84'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parser_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('apartments_parsed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('apartments_created', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('apartments_updated', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('apartments_deactivated', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('trigger', sa.Text(), nullable=False),
    sa.CheckConstraint("status IN ('running', 'success', 'failed')", name='ck_parser_runs_status'),
    sa.CheckConstraint("trigger IN ('schedule', 'manual')", name='ck_parser_runs_trigger'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('residential_complexes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_normalized', sa.Text(), nullable=False),
    sa.Column('city_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_project_id', name='uq_residential_complexes_source_project_id')
    )
    op.create_index('ix_residential_complexes_name_normalized', 'residential_complexes', ['name_normalized'], unique=False)
    op.create_table('apartments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('residential_complex_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('price_base', sa.BigInteger(), nullable=True),
    sa.Column('area', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=False),
    sa.Column('property_type', sa.Text(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('floors_total', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('flat_number', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['residential_complex_id'], ['residential_complexes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', name='uq_apartments_source_id')
    )
    op.create_index('ix_apartments_active_area', 'apartments', ['is_active', 'area'], unique=False, postgresql_where=sa.text('is_active'))
    op.create_index('ix_apartments_active_price', 'apartments', ['is_active', 'price'], unique=False, postgresql_where=sa.text('is_active'))
    op.create_index('ix_apartments_active_residential_complex_id', 'apartments', ['is_active', 'residential_complex_id'], unique=False, postgresql_where=sa.text('is_active'))
    op.create_index('ix_apartments_active_rooms', 'apartments', ['is_active', 'rooms'], unique=False, postgresql_where=sa.text('is_active'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apartments_active_rooms', table_name='apartments', postgresql_where=sa.text('is_active'))
    op.drop_index('ix_apartments_active_residential_complex_id', table_name='apartments', postgresql_where=sa.text('is_active'))
    op.drop_index('ix_apartments_active_price', table_name='apartments', postgresql_where=sa.text('is_active'))
    op.drop_index('ix_apartments_active_area', table_name='apartments', postgresql_where=sa.text('is_active'))
    op.drop_table('apartments')
    op.drop_index('ix_residential_complexes_name_normalized', table_name='residential_complexes')
    op.drop_table('residential_complexes')
    op.drop_table('parser_runs')
    # ### end Alembic commands ###
